import { expect, it } from 'vitest';
import { parseYarnLock } from '../../../src/scanner/lockfiles/yarn-lock-parser.js';

const npmEntry = (name: string, version: string) => ({
      name,
      version,
      ecosystem: 'npm',
      lockfile: 'yarn.lock',
});

it('parses a classic (v1) lockfile with a single spec header', () => {
      const raw = `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


chalk@^5.3.0:
  version "5.3.0"
  resolved "https://registry.yarnpkg.com/chalk/-/chalk-5.3.0.tgz#deadbeef"
  integrity sha512-aaaa
`;

      expect(parseYarnLock(raw)).toEqual([npmEntry('chalk', '5.3.0')]);
});

it('parses a classic lockfile with a multi-spec comma-separated header', () => {
      const raw = `# yarn lockfile v1

chalk@^5.0.0, chalk@^5.3.0:
  version "5.3.0"
  resolved "https://registry.yarnpkg.com/chalk/-/chalk-5.3.0.tgz#deadbeef"
`;

      expect(parseYarnLock(raw)).toEqual([npmEntry('chalk', '5.3.0')]);
});

it('parses a classic lockfile with a quoted scoped header', () => {
      const raw = `# yarn lockfile v1

"@babel/core@^8.0.0":
  version "8.0.1"
  resolved "https://registry.yarnpkg.com/@babel/core/-/core-8.0.1.tgz#deadbeef"
`;

      expect(parseYarnLock(raw)).toEqual([npmEntry('@babel/core', '8.0.1')]);
});

it('skips classic entries with no resolved field or a local resolved source', () => {
      const raw = `# yarn lockfile v1

local-pkg@file:../local-pkg:
  version "0.1.0"

no-resolved@^1.0.0:
  version "1.0.0"

chalk@^5.3.0:
  version "5.3.0"
  resolved "https://registry.yarnpkg.com/chalk/-/chalk-5.3.0.tgz#deadbeef"
`;

      expect(parseYarnLock(raw)).toEqual([npmEntry('chalk', '5.3.0')]);
});

it('parses a Berry (v2+) lockfile via its __metadata marker', () => {
      const raw = `__metadata:
  version: 6
  cacheKey: 8

"chalk@npm:^5.3.0, chalk@npm:^5.0.0":
  version: 5.3.0
  resolution: "chalk@npm:5.3.0"
  checksum: abc
  languageName: node
  linkType: hard

"@babel/core@npm:^8.0.0":
  version: 8.0.1
  resolution: "@babel/core@npm:8.0.1"
  checksum: def
  languageName: node
  linkType: hard
`;

      expect(parseYarnLock(raw)).toEqual(
            expect.arrayContaining([npmEntry('chalk', '5.3.0'), npmEntry('@babel/core', '8.0.1')]),
      );
});

it('skips Berry entries that are not resolved from the npm registry', () => {
      const raw = `__metadata:
  version: 6

"workspace-pkg@workspace:.":
  version: 0.0.0-use.local
  resolution: "workspace-pkg@workspace:."
  languageName: unknown
  linkType: soft

"portal-pkg@portal:../portal-pkg::locator=root%40workspace%3A.":
  version: 1.0.0
  resolution: "portal-pkg@portal:../portal-pkg::locator=root%40workspace%3A."
  languageName: node
  linkType: soft

"chalk@npm:^5.3.0":
  version: 5.3.0
  resolution: "chalk@npm:5.3.0"
  languageName: node
  linkType: hard
`;

      expect(parseYarnLock(raw)).toEqual([npmEntry('chalk', '5.3.0')]);
});

it('returns an empty array (no throw) for an empty file', () => {
      expect(parseYarnLock('')).toEqual([]);
});
